version: '3.8'

services:
  minio-dvc:
    container_name: minio-dvc
    image: minio/minio:RELEASE.2023-12-02T10-51-33Z.hotfix.d45db9b16
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-changeme}
    volumes:
      - minio_data:/data
    ports:
      - "8081:9000"   # MinIO API
      - "8080:9001"   # MinIO Console
    command: server /data --console-address ":9001"
    networks:
      - minio_net

volumes:
  minio_data:

networks:
  minio_net:
    driver: bridge
