version: '3.8'

services:
  minio-dvc:
    container_name: minio-dvc
    image: minio/minio:RELEASE.2023-12-02T10-51-33Z.hotfix.d45db9b16
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-changeme}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090"
    networks:
      - minio_net

volumes:
  minio_data:

networks:
  minio_net:
    driver: bridge
